CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE "users" (
	"id" UUID NOT NULL UNIQUE DEFAULT gen_random_uuid(),
	"email" VARCHAR(255) NOT NULL,
	"pass_hash" BYTEA NOT NULL,
	"name" TEXT,
	"surname" TEXT,
	"avatar_key" TEXT,
	PRIMARY KEY("id")
);

CREATE UNIQUE INDEX "idx_users_email"
ON "users" ("email");

CREATE TABLE "apps" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"name" TEXT NOT NULL,
	"secret" TEXT NOT NULL,
	PRIMARY KEY("id")
);

CREATE TABLE "refresh_tokens" (
	"id" UUID NOT NULL UNIQUE DEFAULT gen_random_uuid(),
	"user_id" UUID NOT NULL,
	"app_id" INTEGER NOT NULL,
	"value" VARCHAR(32) NOT NULL,
	"created_at" TIMESTAMPTZ NOT NULL,
	"expires_at" TIMESTAMPTZ NOT NULL,
	"is_revoked" BOOLEAN NOT NULL DEFAULT false,
	PRIMARY KEY("id")
);